# Welcome to DemonWolf Boilerplate
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in HTML files,
# you will see them access via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the template via {{ site.myvariable }}.
title: "Jekyll Bootstrap Blog"
email: your-email@domain.com
description: Quick starter project for Jekyll Blog including full setup for gulp, Sass, Autoprefixer, Browserify, Imagemin, Browsersync, PostCSS etc. Designed based on bootstrap and FA.
subpath: "" # the subpath of your site, e.g. /blog
github_username: mrdemonwolf
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "post/:year/:title/"
pagination:
  enabled: true
  collection: 'posts'
  title: ':title - page :num'
  permalink: '/post/page/:num/'
  sort_field: 'date'
  sort_reverse: true

# Build settings
markdown: kramdown
permalink: pretty # Enabled pretty urls /test/ other thgemen test.html

plugins:
  - jekyll-feed
  - jekyll-paginate-v2

exclude:
  - Gemfile
  - Gemfile.lock
  - mrdemonwolf.config.js
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
  - Config.MD
